apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: sales-dev
spec:
  image: idatabugs/flink-python:latest
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "10"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: sales-configmap-volume
              mountPath:  /opt/flink/config
              readOnly: true
            - name: python-configmap-volume
              mountPath:  /opt/flink/usrlib
              readOnly: true
      volumes:
        - name: sales-configmap-volume
          configMap:
            name: sales-config
        - name: python-configmap-volume
          configMap:
            name: python-config
  job:
    jarURI: local:///opt/flink/opt/flink-python-1.18.1.jar
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-pyclientexec", "/usr/local/bin/python3", "-py", "/opt/flink/usrlib/sales.py"]
    parallelism: 1
    upgradeMode: stateless